//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrera()
        {
            this.PlanEstudio = new HashSet<PlanEstudio>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public string Abreviacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<short> IdDireccionArea { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Resolucion { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<short> IdNivelEstudio { get; set; }
        public Nullable<int> IdInstitucionProfecional { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCostoNovus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanEstudio> PlanEstudio { get; set; }
    }
}
