//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curriculum()
        {
            this.ExperienciaLaboral = new HashSet<ExperienciaLaboral>();
            this.Habilidad = new HashSet<Habilidad>();
            this.InformacionAdicional = new HashSet<InformacionAdicional>();
            this.Invitado = new HashSet<Invitado>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Postulante = new HashSet<Postulante>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Titulo { get; set; }
        public string Contrato { get; set; }
        public int PretencionSalarial { get; set; }
        public string PresentacionBiografica { get; set; }
        public string PaisResidencia { get; set; }
        public string EstadoRegion { get; set; }
        public string Ciudad { get; set; }
        public int Privacidad { get; set; }
        public string Estado { get; set; }
        public int IdEducacion { get; set; }
        public int IdDatosPersonales { get; set; }
        public int IdCandidato { get; set; }
        public Nullable<int> IdCarrera { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual CarreraBDT CarreraBDT { get; set; }
        public virtual DatosPersonales DatosPersonales { get; set; }
        public virtual Educacion Educacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaLaboral> ExperienciaLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habilidad> Habilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacionAdicional> InformacionAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitado> Invitado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulante> Postulante { get; set; }
    }
}
