//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleo()
        {
            this.Invitado = new HashSet<Invitado>();
            this.Postulante = new HashSet<Postulante>();
            this.CategoriaBDT = new HashSet<CategoriaBDT>();
        }
    
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Contrato { get; set; }
        public string Descripcion { get; set; }
        public string RangoSueldos { get; set; }
        public int ExperienciaMinima { get; set; }
        public string Periodo { get; set; }
        public string Pais { get; set; }
        public string EstadoRegion { get; set; }
        public string Ciudad { get; set; }
        public string CorreoEnvioPostulaciones { get; set; }
        public string Estado { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public Nullable<bool> Teletrabajo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitado> Invitado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulante> Postulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaBDT> CategoriaBDT { get; set; }
    }
}
