//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.InscripcionCarrera = new HashSet<InscripcionCarrera>();
        }
    
        public int Id { get; set; }
        public Nullable<short> AnioEgresoBachiller { get; set; }
        public string NroTitulo { get; set; }
        public int NroFolio { get; set; }
        public string NroFolioPostGrado { get; set; }
        public string Pin { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<short> IdColegio { get; set; }
        public Nullable<int> IdTutor { get; set; }
        public Nullable<short> IdCondicionLaboral { get; set; }
        public Nullable<short> IdTurnoBachiller { get; set; }
        public Nullable<short> IdSede { get; set; }
        public Nullable<short> IdParentesco { get; set; }
        public Nullable<System.DateTime> FechaTituloBachiller { get; set; }
        public Nullable<short> IdUniversidad { get; set; }
        public Nullable<int> IdGrupoDocumento { get; set; }
        public string PersonaReferencia { get; set; }
        public string TelefonoReferencia { get; set; }
        public Nullable<short> IdIdiomaMaterno { get; set; }
        public string Discapacidad { get; set; }
        public Nullable<long> IdMoodleUsuario { get; set; }
        public string EmailOffice365 { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscripcionCarrera> InscripcionCarrera { get; set; }
    }
}
