//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboral
    {
        public int Id { get; set; }
        public string NombreEmpresa { get; set; }
        public string CargoEnEmpresa { get; set; }
        public string ContactoEmpresa { get; set; }
        public string Industria { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool TrabajoActual { get; set; }
        public Nullable<int> NroPersonasAlCargo { get; set; }
        public string Pais { get; set; }
        public string EstadoRegion { get; set; }
        public string Ciudad { get; set; }
        public int IdCurriculum { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
    }
}
