//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionAdicional
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int IdCurriculum { get; set; }
        public string Titulo { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
    }
}
