//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionCarrera
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public short IdPlanEstudio { get; set; }
        public int IdEstudiante { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<short> IdTipoBeneficio { get; set; }
        public Nullable<short> IdSistemaEstudio { get; set; }
        public Nullable<short> IdTurno { get; set; }
        public Nullable<short> IdFormaPago { get; set; }
        public Nullable<short> IdTipoIngreso { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<short> IdSistemaEnsenanza { get; set; }
        public Nullable<int> IdTipoEstudiante { get; set; }
        public Nullable<int> Recargo { get; set; }
        public string NroCertificadoEgreso { get; set; }
        public Nullable<bool> Regular { get; set; }
        public string NroFolio { get; set; }
        public string NroHabilitacion { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual PlanEstudio PlanEstudio { get; set; }
    }
}
