//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invitado()
        {
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public int Id { get; set; }
        public int IdCurriculum { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdEmpleo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string SueldoAproximado { get; set; }
        public string Carta { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdMensaje { get; set; }
        public Nullable<int> idMensajeReceptor { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Empleo Empleo { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Mensaje Mensaje { get; set; }
        public virtual Mensaje Mensaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
    }
}
