//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista
    {
        public int Id { get; set; }
        public string Institucion { get; set; }
        public string CarreraCursoSeminario { get; set; }
        public string Nivel { get; set; }
        public string Pais { get; set; }
        public string EstadoRegion { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool EstudiandoActualmente { get; set; }
        public int IdEducacion { get; set; }
    
        public virtual Educacion Educacion { get; set; }
    }
}
