//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPDS_BDTEntities : DbContext
    {
        public UPDS_BDTEntities()
            : base("name=UPDS_BDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Candidato> Candidato { get; set; }
        public virtual DbSet<CarreraBDT> CarreraBDT { get; set; }
        public virtual DbSet<CategoriaBDT> CategoriaBDT { get; set; }
        public virtual DbSet<Colegio> Colegio { get; set; }
        public virtual DbSet<Curriculum> Curriculum { get; set; }
        public virtual DbSet<DatosPersonales> DatosPersonales { get; set; }
        public virtual DbSet<DepartamentoBDT> DepartamentoBDT { get; set; }
        public virtual DbSet<Educacion> Educacion { get; set; }
        public virtual DbSet<Empleo> Empleo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<ExperienciaLaboral> ExperienciaLaboral { get; set; }
        public virtual DbSet<Habilidad> Habilidad { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<IndustriaBDT> IndustriaBDT { get; set; }
        public virtual DbSet<InformacionAdicional> InformacionAdicional { get; set; }
        public virtual DbSet<Invitado> Invitado { get; set; }
        public virtual DbSet<Lista> Lista { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Postulante> Postulante { get; set; }
        public virtual DbSet<ProfesionOcupacionBDT> ProfesionOcupacionBDT { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
