//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public string Estado { get; set; }
        public string Emisor { get; set; }
        public string Receptor { get; set; }
        public Nullable<int> IdPostulante { get; set; }
        public Nullable<int> IdInvitado { get; set; }
        public Nullable<int> IdEmpresaReceptor { get; set; }
        public Nullable<int> IdCurriculum { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Invitado Invitado { get; set; }
        public virtual Postulante Postulante { get; set; }
    }
}
