//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<short> IdTipoDocumento { get; set; }
        public string DocumentoIdentidad { get; set; }
        public Nullable<short> IdCiudadDocumentoIdentidad { get; set; }
        public string Direccion { get; set; }
        public string TelefonoDomicilio { get; set; }
        public string Celular { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string SitioWeb { get; set; }
        public string Facebook { get; set; }
        public string InstitucionTrabajo { get; set; }
        public string DireccionTrabajo { get; set; }
        public string TelefonoTrabajo { get; set; }
        public Nullable<short> IdSexo { get; set; }
        public Nullable<int> NIT { get; set; }
        public string Observacion { get; set; }
        public string Fax { get; set; }
        public string Foto { get; set; }
        public Nullable<short> IdEstadoCivil { get; set; }
        public Nullable<short> IdTipoSangre { get; set; }
        public Nullable<short> IdCiudad { get; set; }
        public Nullable<short> IdNacionalidad { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<bool> TieneFoto { get; set; }
        public Nullable<int> IdRN { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Ciudad Ciudad { get; set; }
    }
}
