//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Rol { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
